import Link from 'next/link'

const EFFECTIVE_DATE = 'April 1, 2026'

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-8">
      <h2 className="mb-3 font-heading text-lg font-bold text-foreground">{title}</h2>
      <div className="space-y-3 text-sm leading-relaxed text-muted-foreground">{children}</div>
    </div>
  )
}

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6">
      <div className="mb-10">
        <h1 className="font-heading text-3xl font-bold text-foreground">Terms of Service</h1>
        <p className="mt-2 text-sm text-muted-foreground">Effective date: {EFFECTIVE_DATE}</p>
      </div>

      <div className="mb-8 rounded-xl border border-yellow-500/20 bg-yellow-500/5 px-5 py-4 text-sm text-muted-foreground">
        <strong className="text-foreground">Important:</strong> By using SWARM Marketplace you agree to these terms. If you do not agree, do not use the platform.
      </div>

      <Section title="1. The Service">
        <p>SWARM Marketplace ("SWARM") is a non-custodial platform that enables users to discover, call, and publish AI skills settled via the Solana blockchain. SWARM acts as an intermediary proxy only — it does not hold funds, does not guarantee skill quality, and is not a financial service provider.</p>
      </Section>

      <Section title="2. Eligibility">
        <p>You must be at least 18 years old and legally permitted to use blockchain-based services in your jurisdiction. By connecting a wallet you represent that you meet these requirements.</p>
        <p>SWARM is not available in jurisdictions where its use would violate local law. It is your responsibility to determine whether SWARM is legal in your location.</p>
      </Section>

      <Section title="3. Wallet and payments">
        <p>SWARM is non-custodial. You retain full control of your private keys and funds at all times. SWARM never has access to your wallet's private key.</p>
        <p>Blockchain transactions are irreversible. Before signing any transaction, verify the details. SWARM is not liable for losses caused by user error, incorrect addresses, or failed transactions.</p>
        <p>Escrow refunds are handled on-chain via the <code className="text-[#9945FF]">escrow_payment</code> program. SWARM cannot manually intervene in on-chain escrow accounts.</p>
      </Section>

      <Section title="4. Publishing skills">
        <p>By publishing a skill you represent that you have the right to offer the skill and that its output does not infringe third-party intellectual property rights.</p>
        <p>You are responsible for the availability and behaviour of your skill. Repeated failures, harmful outputs, or violations of the <Link href="/usage" className="text-[#9945FF] hover:underline">Usage Policy</Link> may result in your skill being de-listed.</p>
        <p>SWARM takes a {5}% platform fee on each paid call. See the full <Link href="/fees" className="text-[#9945FF] hover:underline">Fee Schedule</Link>.</p>
      </Section>

      <Section title="5. Prohibited conduct">
        <ul className="ml-4 list-disc space-y-1">
          <li>Using SWARM to generate, distribute, or facilitate illegal content</li>
          <li>Circumventing payment mechanisms or attempting to call skill endpoints directly</li>
          <li>Publishing skills that impersonate other people or organisations</li>
          <li>Automated abuse, scraping, or denial-of-service attacks</li>
          <li>Using SWARM for money laundering or sanctions evasion</li>
        </ul>
        <p>Violations may result in immediate de-listing of your skills and wallet-level bans.</p>
      </Section>

      <Section title="6. Disclaimers">
        <p>SWARM IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. WE DO NOT WARRANT THAT SKILLS WILL BE ACCURATE, UNINTERRUPTED, OR ERROR-FREE. SKILL OUTPUTS ARE GENERATED BY THIRD-PARTY AI MODELS AND SHOULD NOT BE RELIED UPON AS PROFESSIONAL ADVICE (LEGAL, FINANCIAL, MEDICAL, ETC.).</p>
      </Section>

      <Section title="7. Limitation of liability">
        <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, SWARM AND ITS CONTRIBUTORS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOSS OF FUNDS, DATA, OR PROFITS, ARISING FROM YOUR USE OF THE PLATFORM.</p>
      </Section>

      <Section title="8. Changes to these terms">
        <p>We may update these terms. Material changes will be announced on{' '}
          <a href="https://x.com/swarm_market" target="_blank" rel="noopener noreferrer" className="text-[#9945FF] hover:underline">X / Twitter</a>{' '}
          and on this page with at least 7 days notice. Continued use after changes constitutes acceptance.
        </p>
      </Section>

      <Section title="9. Governing law">
        <p>These terms are governed by the laws of the jurisdiction in which SWARM is incorporated, without regard to conflict-of-law provisions. Disputes shall be resolved through binding arbitration where permitted by law.</p>
      </Section>

      <div className="rounded-xl border bg-card px-6 py-4 text-sm text-muted-foreground" style={{ borderColor: 'var(--border-subtle)' }}>
        Questions about these terms? Open an issue on{' '}
        <a href="https://github.com/windyinwind/swarm-marketplace/issues" target="_blank" rel="noopener noreferrer" className="text-[#9945FF] hover:underline">GitHub</a>.
      </div>
    </div>
  )
}
