[toolchain]
anchor_version = "1.0.0"

[features]
seeds = true
skip-lint = false

[programs.localnet]
skill_registry = "Cu3AA9kASqXYTvf3YnLCMJYyYszSyeK56jFMgo9wZxfA"
escrow_payment  = "8GHDWw5XsN39zVGPryYcSNaanxjAfT5jWbmaoNb7e9mx"

[programs.devnet]
skill_registry = "Cu3AA9kASqXYTvf3YnLCMJYyYszSyeK56jFMgo9wZxfA"
escrow_payment  = "8GHDWw5XsN39zVGPryYcSNaanxjAfT5jWbmaoNb7e9mx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
